<a href="https://colab.research.google.com/github/Madushani-Weerasekara/D9_Word-embedding-Techniques/blob/main/D9_Word_embedding_Techniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Word Embedding Techniques Using Embedding Layers in Keras

In [2]:
# Libraries use tensorflow >2.15.0 and keras

In [3]:
!pip install tensorflow-gpu

  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [1]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [4]:
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
# Sentences
sent = [  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
# Vocabulary size
voc_size = 500

##One Hot Representation

In [9]:
onehot_rep = [one_hot(words,voc_size) for words in sent]
print(onehot_rep)

[[441, 139, 302, 91], [441, 139, 302, 63], [441, 167, 302, 446], [312, 66, 232, 474, 48], [312, 66, 232, 474, 304], [24, 441, 481, 302, 46], [481, 61, 117, 474]]


##Word Embedding Representation

In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [12]:
## Prepadding
sent_length = 8
embedded_docs = pad_sequences(onehot_rep,padding ="pre", maxlen=sent_length)
print(embedded_docs)


[[  0   0   0   0 441 139 302  91]
 [  0   0   0   0 441 139 302  63]
 [  0   0   0   0 441 167 302 446]
 [  0   0   0 312  66 232 474  48]
 [  0   0   0 312  66 232 474 304]
 [  0   0   0  24 441 481 302  46]
 [  0   0   0   0 481  61 117 474]]


In [13]:
## Postpadding
sent_length = 8
embedded_docs = pad_sequences(onehot_rep, padding ='post', maxlen=sent_length)
print(embedded_docs)

[[441 139 302  91   0   0   0   0]
 [441 139 302  63   0   0   0   0]
 [441 167 302 446   0   0   0   0]
 [312  66 232 474  48   0   0   0]
 [312  66 232 474 304   0   0   0]
 [ 24 441 481 302  46   0   0   0]
 [481  61 117 474   0   0   0   0]]


In [14]:
# 10 feature dimension
dim = 10

In [17]:
model=Sequential()
model.add(Embedding(voc_size, 10, input_length=sent_length))
model.compile("adam", 'mse')

In [18]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5000 (19.53 KB)
Trainable params: 5000 (19.53 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
