<a href="https://colab.research.google.com/github/Madushani-Weerasekara/D9_Word-embedding-Techniques/blob/main/D9_Word_embedding_Techniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Word Embedding Techniques Using Embedding Layers in Keras

In [2]:
# Libraries use tensorflow >2.15.0 and keras

In [3]:
!pip install tensorflow-gpu

  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [1]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [4]:
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
# Sentences
sent = [  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
# Vocabulary size
voc_size = 500

##One Hot Representation

In [9]:
onehot_rep = [one_hot(words,voc_size) for words in sent]
print(onehot_rep)

[[441, 139, 302, 91], [441, 139, 302, 63], [441, 167, 302, 446], [312, 66, 232, 474, 48], [312, 66, 232, 474, 304], [24, 441, 481, 302, 46], [481, 61, 117, 474]]


##Word Embedding Representation

In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [12]:
## Prepadding
sent_length = 8
embedded_docs = pad_sequences(onehot_rep,padding ="pre", maxlen=sent_length)
print(embedded_docs)


[[  0   0   0   0 441 139 302  91]
 [  0   0   0   0 441 139 302  63]
 [  0   0   0   0 441 167 302 446]
 [  0   0   0 312  66 232 474  48]
 [  0   0   0 312  66 232 474 304]
 [  0   0   0  24 441 481 302  46]
 [  0   0   0   0 481  61 117 474]]


In [13]:
## Postpadding
sent_length = 8
embedded_docs = pad_sequences(onehot_rep, padding ='post', maxlen=sent_length)
print(embedded_docs)

[[441 139 302  91   0   0   0   0]
 [441 139 302  63   0   0   0   0]
 [441 167 302 446   0   0   0   0]
 [312  66 232 474  48   0   0   0]
 [312  66 232 474 304   0   0   0]
 [ 24 441 481 302  46   0   0   0]
 [481  61 117 474   0   0   0   0]]


In [14]:
# 10 feature dimension
dim = 10

In [17]:
model=Sequential()
model.add(Embedding(voc_size, 10, input_length=sent_length))
model.compile("adam", 'mse')

In [18]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5000 (19.53 KB)
Trainable params: 5000 (19.53 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [20]:
# The glass of milk
embedded_docs[0]

array([441, 139, 302,  91,   0,   0,   0,   0], dtype=int32)

In [21]:
# your videos are good
embedded_docs[6]

array([481,  61, 117, 474,   0,   0,   0,   0], dtype=int32)

In [23]:
model.predict(embedded_docs[0])
#The following result shows each word represented by 10 dimensions.

1/1 [==============================] - 0s 28ms/step


array([[-0.03105428, -0.00071339, -0.02140129, -0.04467808, -0.0091626 ,
         0.00977386,  0.00354705,  0.0008135 ,  0.02015326,  0.00410227],
       [-0.00843029,  0.02226904, -0.01564329,  0.01314769, -0.04697592,
         0.02429267,  0.01562161,  0.02086078,  0.03656905, -0.00167342],
       [-0.02517401,  0.00852076,  0.02486886, -0.04974542,  0.00436633,
        -0.00822463, -0.02553901,  0.01210005,  0.00696037, -0.04459512],
       [-0.00667031, -0.0376334 , -0.01016378, -0.04715496, -0.00801492,
         0.02967191, -0.04770509, -0.04711208, -0.018568  , -0.0275545 ],
       [-0.02286749, -0.04086603, -0.01848356,  0.03928048, -0.0414536 ,
         0.04761601, -0.03502075, -0.02891975, -0.03334425, -0.02250222],
       [-0.02286749, -0.04086603, -0.01848356,  0.03928048, -0.0414536 ,
         0.04761601, -0.03502075, -0.02891975, -0.03334425, -0.02250222],
       [-0.02286749, -0.04086603, -0.01848356,  0.03928048, -0.0414536 ,
         0.04761601, -0.03502075, -0.02891975

In [24]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 61ms/step
[[[-0.03105428 -0.00071339 -0.02140129 -0.04467808 -0.0091626
    0.00977386  0.00354705  0.0008135   0.02015326  0.00410227]
  [-0.00843029  0.02226904 -0.01564329  0.01314769 -0.04697592
    0.02429267  0.01562161  0.02086078  0.03656905 -0.00167342]
  [-0.02517401  0.00852076  0.02486886 -0.04974542  0.00436633
   -0.00822463 -0.02553901  0.01210005  0.00696037 -0.04459512]
  [-0.00667031 -0.0376334  -0.01016378 -0.04715496 -0.00801492
    0.02967191 -0.04770509 -0.04711208 -0.018568   -0.0275545 ]
  [-0.02286749 -0.04086603 -0.01848356  0.03928048 -0.0414536
    0.04761601 -0.03502075 -0.02891975 -0.03334425 -0.02250222]
  [-0.02286749 -0.04086603 -0.01848356  0.03928048 -0.0414536
    0.04761601 -0.03502075 -0.02891975 -0.03334425 -0.02250222]
  [-0.02286749 -0.04086603 -0.01848356  0.03928048 -0.0414536
    0.04761601 -0.03502075 -0.02891975 -0.03334425 -0.02250222]
  [-0.02286749 -0.04086603 -0.01848356  0.03928048 -0.0414536
 

In [25]:
embedded_docs[0]

array([441, 139, 302,  91,   0,   0,   0,   0], dtype=int32)

In [26]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 21ms/step
[[-0.03105428 -0.00071339 -0.02140129 -0.04467808 -0.0091626   0.00977386
   0.00354705  0.0008135   0.02015326  0.00410227]
 [-0.00843029  0.02226904 -0.01564329  0.01314769 -0.04697592  0.02429267
   0.01562161  0.02086078  0.03656905 -0.00167342]
 [-0.02517401  0.00852076  0.02486886 -0.04974542  0.00436633 -0.00822463
  -0.02553901  0.01210005  0.00696037 -0.04459512]
 [-0.00667031 -0.0376334  -0.01016378 -0.04715496 -0.00801492  0.02967191
  -0.04770509 -0.04711208 -0.018568   -0.0275545 ]
 [-0.02286749 -0.04086603 -0.01848356  0.03928048 -0.0414536   0.04761601
  -0.03502075 -0.02891975 -0.03334425 -0.02250222]
 [-0.02286749 -0.04086603 -0.01848356  0.03928048 -0.0414536   0.04761601
  -0.03502075 -0.02891975 -0.03334425 -0.02250222]
 [-0.02286749 -0.04086603 -0.01848356  0.03928048 -0.0414536   0.04761601
  -0.03502075 -0.02891975 -0.03334425 -0.02250222]
 [-0.02286749 -0.04086603 -0.01848356  0.03928048 -0.0414536   0.04761601